[build]
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  from = "/.netlify/functions/webhook"
  to = "/.netlify/functions/webhook"
  status = 200



