[build]
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/rateLimiter"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/rateLimiter"
  status = 200
  force = true
