[build]
  publish = "build"
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[[edge_functions]]
  function = "rateLimiter"
  path = "/rateLimiter"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
