[build]
  publish = "build"
  functions = "netlify/functions"
  edge_functions = "dist"

[[edge_functions]]
  path = "/*"
  function = "rateLimiter"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
