[build]
  publish = "build"
  functions = "netlify/functions"

[[edge_functions]]
  function = "rateLimiter"
  path = "netlify/edge-functions/rateLimiter.js"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
